### ISSUE TITLE
Broadcast votes to our current sections and their neighbours

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/ewok#22]
Even if we are disconnected from some nodes which we consider current, we should send messages to them and expect the network to eventually deliver them. In a real network, this could be achieved by keeping a message queue for each disconnected node, but for now we can let the `Network` struct act as the message queue.

**Comment by Fraser999** [comment]
We've decided rather than simulating a particular implementation for ensuring delivery, we'll keep Ewok blissfully unaware of the details and just have the network deliver all messages, regardless of whether the two endpoints are connected or not.
