### ISSUE TITLE
Seperate events and messages into distinct types

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/ewok#23]
We should differentiate between these two so that the code makes more sense. However, lets keep using the `Network` to send both events and messages for now, as that saves us from duplicating the delayed delivery behaviour.

**Comment by michaelsproul** [comment]
I had a go at implementing this here: https://github.com/michaelsproul/ewok/tree/event-vs-message

It works, but I'm not *super* convinced it's worth the increase in complexity...

**Comment by Fraser999** [comment]
Yeah - I'd probably vote to close this issue, but don't feel strongly either way.
