### ISSUE TITLE
Allow setting the simulation up with a fixed set of nodes and events

### ISSUE THREAD

**Issue by michaelsproul** [michaelsproul/ewok#8]
Something like: there are 5 sections, they have these prefixes, they contain these nodes.

Then: add node X at step 0, add node Y at step 5, remove node Z at step 11, etc.

**Comment by michaelsproul** [comment]
In progress here: https://github.com/michaelsproul/ewok/pull/20

**Comment by Fraser999** [comment]
Closed by #28.
